### ISSUE TITLE
Error trying to import file

### ISSUE THREAD

**Issue by aleprovencio** [X-Ryl669/BwareArea#10]
Hello, I'm getting the error "Only IGO .txt and GPX format are supported" when trying to import a file with this content:

```
X,Y,TYPE,SPEED,DirType,Direction
-44.058251,-19.945982,1,30,1,339
-54.629503,-20.497509,1,30,1,263
-54.646202,-20.496151,1,30,1,86
-34.871705,-8.063943,1,30,1,27
-44.091283,-19.908390,1,30,1,193
...
```

**Comment by X-Ryl669** [comment]
Please make sure your file ends with `.txt` extension if it's a iGO format (the error you've written happens if the file does not have the right extension).

If this still does not work, please send me the file so I can debug it.

**Comment by aleprovencio** [comment]
Thanks for the reply and yes, it does have the ``.txt`` extension. It is actually a file exported from [maparadar](www.maparadar.com).
[maparadar2.txt](https://github.com/X-Ryl669/BwareArea/files/4036123/maparadar2.txt)

**Comment by X-Ryl669** [comment]
Strange... The code is doing this:

```
// Try to figure out if it's txt or gpx.
                // Since Android is not able to figure out a GPX is a text/xml, we need some way to solve this out.
                String[] segments = data.getData().getLastPathSegment().split("\\.");
                String ext = "";
                if (segments.length > 1) ext = segments[1];
                if (ext.equalsIgnoreCase("gpx"))
                {
                     [...]
                } else if (ext.equalsIgnoreCase("txt"))
                {
                    // Likely txt
                     [...]
                } else
                {
                    Toast.makeText(this, "Only iGO .txt and GPX format are supported", Toast.LENGTH_LONG).show();
                }
```
Do you have more than one extension (like `a.b.txt`) ?

**Comment by aleprovencio** [comment]
Alright, I could make it work my renaming `maparadar2.txt` to `speedcam.txt` and moving the file to a more obvious folder (i.e. `Downloads`), so either of this is what it takes :)

Thank you

**Comment by X-Ryl669** [comment]
I'm just curious about what was the original complete path to the file, so I can understand and fix the code ?

**Comment by aleprovencio** [comment]
Sure, lives on `Android/media/com.nextcloud.client/nextcloud/aleprovencio/Documents/speedcam.txt`

Thanks again for you help

**Comment by X-Ryl669** [comment]
This is the working path. Do you have the failing path ?

**Comment by aleprovencio** [comment]
No this was actually the failing path, it worked under `Downloads/speedcam.txt`.

By the time I get home I'll try to investigate this myself with further tests so maybe I can help you somehow.

**Comment by aleprovencio** [comment]
OK I confirm it's not a filename problem and indeed a path issue. Maybe when your app receives the nextcloud path, it is as an URI format like `content://com.android.externalstorage.documents/document/primary%3AAndroid%2Fmedia%2Fcom.nextcloud.client...%2Fspeedcam.txt`. Hope by checking this output you can figure it out.
