### ISSUE TITLE
app crashes on starting the service

### ISSUE THREAD

**Issue by leggewie** [X-Ryl669/BwareArea#2]
Thank you for providing this app.  I got it from f-droid and tested it on my Marshmallow device.  I can run the app, but when I click on "start service" I am notified that "Unfortunately, BwareArea has stopped".

**Comment by X-Ryl669** [comment]
Can you send me the content of the logcat ? (at least the last exception callstack ?)

**Comment by X-Ryl669** [comment]
I realized that getting the logcat is complex if you are not a developer. So here's a link for a debug version of the application (you need to uninstall your version first) that's reporting errors in a dialog so you can copy & paste directly here.

I've tried with a Android M emulator, and I found a bug. The version below has it fixed, but since I'm not 100% sure it's working before releasing, please report.


https://transfernow.net/569fm6c8tfgs

Thanks for reporting bugs.

**Comment by Butanal** [comment]
Hi ! Sorry to hijack, but I have the same issue, and it seems that the newer release (if it is the previously posted fix) is not compiled to fdroid repos. Would it be possible to, at least, provide a non-expiring link to a compiled version of the fixed version ? Thanks, I'd love to use this app !

**Comment by X-Ryl669** [comment]
Yes of course. I don't know why it did not appear on F-Droid yet. I'll post a release on the release page and let you know.

**Comment by X-Ryl669** [comment]
It's done, please check the release page for the APK version. Cheers!

**Comment by leggewie** [comment]
Thanks!

You forgot to increase versionName and versionCode.  Please publish the necessary changes as a new release as proposed in PR #6.

**Comment by IzzySoft** [comment]
Note that for F-Droid to pick up the new version, the tag must point to a commit that already has the increased versionCode/versionName. Currently, v0.6.3 does *not.*

**Comment by X-Ryl669** [comment]
Right, sorry, this seems too complex to me. So, I'm tagging and releasing version 3 with tag 0.6.5.

**Comment by IzzySoft** [comment]
That definitely tackles and solves that issue, thanks! I just checked, and IMHO F-Droid should pick up v0.6.5 on its next run as the commit hash this time points to a commit having the corresponding versionName/Code set. :+1:

PS: If it doesn't, and you still cannot even find it listed in [Apps to Update](https://f-droid.org/wiki/page/Category:Apps_to_Update) within a week, feel free to ping me again for a check.

**Comment by leggewie** [comment]
I'm happy to report that 0.6.5 landed in f-droid.org and that the service now starts appropriately.

Thanks!
