### ISSUE TITLE
Crash when starting service

### ISSUE THREAD

**Issue by 0uro** [X-Ryl669/BwareArea#4]
Hi, love your idea and the way you did it ^^

I tried the F-Droid version and the version you provided here : https://github.com/X-Ryl669/BwareArea/issues/2

But problem remains.

I attached the logcat file 
[bware_aera_log.txt](https://github.com/X-Ryl669/BwareArea/files/2268076/bware_aera_log.txt)

**Comment by X-Ryl669** [comment]
Thanks for the log. I'll fix this ASAP

**Comment by X-Ryl669** [comment]
Please find a version that should have it fixed here:
https://transfernow.net/7520e6x3caf1

Let me know if it worked for you, so I can commit the change to the repository and prepare a new release.

**Comment by 0uro** [comment]
Okay, that fixed it. Tried some torture tests and it's stable.

Great work :)
